@startuml
class MeshRenderer {
    + MeshRenderer()
    + MeshRenderer(_mesh:Mesh)
    + MeshRenderer(_model:Model)
    + MeshRenderer(_meshes:Mesh[], _materials:Material[])
    + <<override>> <<unsafe>> Start() : void
    + <<override>> Exit() : void
}
Component <|-- MeshRenderer
MeshRenderer --> "material" Material
MeshRenderer --> "mesh" Mesh
MeshRenderer o-> "renderOrder" RenderOrder
@enduml
