@startuml
class Shader {
    + Shader(_vertexPath:string, _fragmentPath:string)
    + Bind() : void
    + Use() : void
    + Dispose() : void
    + GetUniformLocation(_name:string) : int
}
IDisposable <|-- Shader
Shader --> "lit" Shader
Shader --> "unlit" Shader
Shader --> "test" Shader
@enduml
