@startuml
enum TextureFilter {
    Linear,
    Point,
}
class Texture2D {
    + name : string
    + generateMipmap : bool = true
    + Texture2D(_path:string)
    + Texture2D()
    + Texture2D(_c:Colour)
    + Bind(_unit:int) : void
    + Use() : void
}
Texture2D --> "textureFilter" TextureFilter
Texture2D o-> "wrapMode" TextureWrapMode
@enduml
