@startuml
class Game {
    + {static} isInitialized : bool = false
    + <<unsafe>> Run() : void
}
class "Action`1"<T> {
}
Game --> "InitCall" Action
Game --> "UpdateCall<float>" "Action`1"
Game --> "LateUpdateCall" Action
Game --> "EarlyRenderCall" Action
Game --> "RenderCall" Action
Game --> "LateRenderCall" Action
Game --> "ExitCall" Action
@enduml
